name: Build and Deploy to Render

on:
  push:
    branches:
      - cicd-creation  # Change this to your default branch if it's not main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t krithikpatil/research_gpt:latest .
  
    - name: Push Docker image to Docker Hub
      run: |
        docker push krithikpatil/research_gpt:latest

    - name: Deploy to Render
      run: |
        curl -X POST https://api.onrender.com/v1/services/${{secrets.RESEARCH_GPT_SERVICE_ID}}/deploy \
          -H "Authorization: Bearer ${{ secrets.ONRENDER_API_KEY }}"